# Generated by Django 4.1.5 on 2023-10-31 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_code', models.CharField(blank=True, max_length=15, null=True)),
                ('vchr_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('vchr_district', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=100)),
                ('vchr_sales_type', models.CharField(max_length=100)),
                ('int_order', models.IntegerField()),
                ('int_active', models.IntegerField()),
            ],
            options={
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='StatusChart',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('int_order', models.IntegerField()),
                ('int_active', models.IntegerField()),
            ],
            options={
                'db_table': 'status_chart',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('chr_status', models.CharField(blank=True, max_length=1, null=True)),
                ('vchr_gst_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fk_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service_app.country')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('vchr_customer_name', models.CharField(max_length=50)),
                ('bint_cust_phone', models.IntegerField(blank=True, null=True)),
                ('dbl_amt_paid', models.FloatField(blank=True, null=True)),
                ('dbl_total_amt', models.FloatField(blank=True, null=True)),
                ('dbl_service_charge', models.FloatField(blank=True, null=True)),
                ('vchr_reference_num', models.CharField(max_length=50)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
                ('int_order', models.IntegerField()),
                ('int_active', models.IntegerField()),
                ('fk_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user', to=settings.AUTH_USER_MODEL)),
                ('fk_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_location', to='service_app.location')),
                ('fk_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_text', to='service_app.statuschart')),
                ('fk_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_master',
            },
        ),
        migrations.CreateModel(
            name='ServiceFollowup',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('vchr_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dbl_paid_amt', models.FloatField(blank=True, null=True)),
                ('fk_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fk_master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_app.servicemaster')),
                ('fk_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_status', to='service_app.statuschart')),
            ],
            options={
                'db_table': 'service_followup',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='fk_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service_app.states'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fk_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service_app.states')),
            ],
            options={
                'db_table': 'district',
            },
        ),
    ]
